spring:
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

security:
  user:
    password: password
    role: USER
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()
    resource:
      user-info-uri: /user
      
server:
  port: 9999
  context-path: /uaa
  
logging:
  level:
    org.springframework.security: DEBUG